//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Hql.g4 by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419



using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="HqlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public interface IHqlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery([NotNull] HqlParser.QueryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bracesComplexExpression</c>
	/// labeled alternative in <see cref="HqlParser.complexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracesComplexExpression([NotNull] HqlParser.BracesComplexExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multipleComplexExpression</c>
	/// labeled alternative in <see cref="HqlParser.complexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultipleComplexExpression([NotNull] HqlParser.MultipleComplexExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>rangeExpression</c>
	/// labeled alternative in <see cref="HqlParser.complexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeExpression([NotNull] HqlParser.RangeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>andComplexExpression</c>
	/// labeled alternative in <see cref="HqlParser.complexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndComplexExpression([NotNull] HqlParser.AndComplexExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>orComplexExpression</c>
	/// labeled alternative in <see cref="HqlParser.complexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrComplexExpression([NotNull] HqlParser.OrComplexExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>notComplexExpression</c>
	/// labeled alternative in <see cref="HqlParser.complexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotComplexExpression([NotNull] HqlParser.NotComplexExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>termExpression</c>
	/// labeled alternative in <see cref="HqlParser.complexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermExpression([NotNull] HqlParser.TermExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.termExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermExpr([NotNull] HqlParser.TermExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.existsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExistsExpr([NotNull] HqlParser.ExistsExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.rangeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeExpr([NotNull] HqlParser.RangeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd([NotNull] HqlParser.AndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr([NotNull] HqlParser.OrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.not"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot([NotNull] HqlParser.NotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.eq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEq([NotNull] HqlParser.EqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange([NotNull] HqlParser.RangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.contains"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContains([NotNull] HqlParser.ContainsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.search"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSearch([NotNull] HqlParser.SearchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.dateValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateValue([NotNull] HqlParser.DateValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.floatValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatValue([NotNull] HqlParser.FloatValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.intValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntValue([NotNull] HqlParser.IntValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate([NotNull] HqlParser.DateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTime([NotNull] HqlParser.TimeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] HqlParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.phrase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhrase([NotNull] HqlParser.PhraseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] HqlParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.phraseOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhraseOptions([NotNull] HqlParser.PhraseOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.numberValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberValue([NotNull] HqlParser.NumberValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.stringValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringValue([NotNull] HqlParser.StringValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HqlParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] HqlParser.ValueContext context);
}
